-- return {
--     "zbirenbaum/copilot.lua",
--     cmd = "Copilot",
--     event = "InsertEnter",
--     config = function()
--         require("copilot").setup({
--             panel = {
--                 enabled = true,
--                 auto_refresh = false,
--                 keymap = {
--                     jump_prev = "[[",
--                     jump_next = "]]",
--                     accept = "<CR>",
--                     refresh = "gr",
--                     open = "<M-CR>"
--                 },
--                 layout = {
--                     ratio = 0.4
--                 },
--             },
--             suggestion = {
--                 enabled = true,
--                 auto_trigger = true,
--                 debounce = 75,
--                 keymap = {
--                     accept = "<M-y>",
--                     accept_word = false,
--                     accept_line = false,
--                     next = "<M-]>",
--                     prev = "<M-[>",
--                     dismiss = "<C-]>",
--                 },
--             },
--             filetypes = {
--                 yaml = false,
--                 markdown = false,
--                 help = false,
--                 gitcommit = false,
--                 gitrebase = false,
--                 hgcommit = false,
--                 svn = false,
--                 cvs = false,
--                 ["."] = false,
--             },
--             copilot_node_command = 'node', -- Node.js version must be > 18.x
--             server_opts_overrides = {},
--         })
--
--         local map = function(mode, keys, func, desc)
--             desc = 'Copilot: ' .. desc
--             vim.keymap.set(mode, keys, func, { desc = desc })
--         end
--
--         map('n', '<leader>ct', function()
--             vim.cmd([[Copilot toggle]])
--             vim.cmd([[Copilot status]])
--         end, '[c]opilot [t]oggle')
--     end
-- }

return {}
