local config = require('panda.colorscheme.init').config
local colors = require('panda.colorscheme.palette').palette

-- Separar estas weas para que sea mas ordenado
local groups = {
    -- Base groups
    base00 = { fg = colors.base00 },
    base01 = { fg = colors.base01 },
    base02 = { fg = colors.base02 },
    base03 = { fg = colors.base03 },
    base04 = { fg = colors.base04 },
    base05 = { fg = colors.base05 },
    base06 = { fg = colors.base06 },
    base07 = { fg = colors.base07 },
    base08 = { fg = colors.base08 },
    base08Bold = { fg = colors.base08, bold = config.bold },
    base0B = { fg = colors.base0B },
    base0BBold = { fg = colors.base0B, bold = config.bold },
    base0A = { fg = colors.base0A },
    base0ABold = { fg = colors.base0A, bold = config.bold },
    base0D = { fg = colors.base0D },
    base0DBold = { fg = colors.base0D, bold = config.bold },
    base0E = { fg = colors.base0E },
    base0EBold = { fg = colors.base0E, bold = config.bold },
    base0C = { fg = colors.base0C },
    base0CBold = { fg = colors.base0C, bold = config.bold },
    base09 = { fg = colors.base09 },
    base09Bold = { fg = colors.base09, bold = config.bold },
    base08Sign = { fg = colors.base08, bg = colors.base01, reverse = config.invert_signs },
    base0BSign = { fg = colors.base0B, bg = colors.base01, reverse = config.invert_signs },
    base0ASign = { fg = colors.base0A, bg = colors.base01, reverse = config.invert_signs },
    base0DSign = { fg = colors.base0D, bg = colors.base01, reverse = config.invert_signs },
    base0ESign = { fg = colors.base0E, bg = colors.base01, reverse = config.invert_signs },
    base0CSign = { fg = colors.base0C, bg = colors.base01, reverse = config.invert_signs },
    base09Sign = { fg = colors.base09, bg = colors.base01, reverse = config.invert_signs },
    base08Underline = { undercurl = config.undercurl, sp = colors.base08 },
    base0BUnderline = { undercurl = config.undercurl, sp = colors.base0B },
    base0AUnderline = { undercurl = config.undercurl, sp = colors.base0A },
    base0DUnderline = { undercurl = config.undercurl, sp = colors.base0D },
    base0EUnderline = { undercurl = config.undercurl, sp = colors.base0E },
    base0CUnderline = { undercurl = config.undercurl, sp = colors.base0C },
    base09Underline = { undercurl = config.undercurl, sp = colors.base09 },
    Normal = config.transparent_mode and { fg = colors.base05, bg = nil } or { fg = colors.base05, bg = colors.base00 },
    NormalNC = config.dim_inactive and { fg = colors.base04, bg = colors.base01 } or { link = "Normal" },
    CursorLine = { bg = colors.base01 },
    CursorColumn = { link = "CursorLine" },
    TabLineFill = { fg = colors.base03, bg = colors.base01, reverse = config.invert_tabline },
    TabLineSel = { fg = colors.base0B, bg = colors.base01, reverse = config.invert_tabline },
    TabLine = { link = "TabLineFill" },
    MatchParen = { bg = colors.base03, bold = config.bold },
    ColorColumn = { bg = colors.base01 },
    Conceal = { fg = colors.base0D },
    CursorLineNr = { fg = colors.base0A, bg = colors.base01 },
    NonText = { link = "base02" },
    SpecialKey = { link = "base07" },
    Visual = { bg = colors.base03, reverse = config.invert_selection },
    VisualNOS = { link = "Visual" },
    Search = { fg = colors.base0A, bg = colors.base00, reverse = config.inverse },
    IncSearch = { fg = colors.base09, bg = colors.base00, reverse = config.inverse },
    CurSearch = { link = "IncSearch" },
    QuickFixLine = { fg = colors.base00, bg = colors.base0A, bold = config.bold },
    Underlined = { fg = colors.base0D, underline = config.underline },
    StatusLine = { fg = colors.base02, bg = colors.base05, reverse = config.inverse },
    StatusLineNC = { fg = colors.base01, bg = colors.base07, reverse = config.inverse },
    WinBar = { fg = colors.base07, bg = colors.base00 },
    WinBarNC = { fg = colors.base07, bg = colors.base01 },
    VertSplit = { fg = colors.base03, bg = colors.base00 },
    WildMenu = { fg = colors.base0D, bg = colors.base02, bold = config.bold },
    Directory = { link = "base0DBold" },
    Title = { link = "base0BBold" },
    ErrorMsg = { fg = colors.base00, bg = colors.base08, bold = config.bold },
    MoreMsg = { link = "base0ABold" },
    ModeMsg = { link = "base0ABold" },
    Question = { link = "base09Bold" },
    WarningMsg = { link = "base08Bold" },
    LineNr = { fg = colors.base03 },
    SignColumn = config.transparent_mode and { bg = nil } or { bg = colors.base01 },
    Folded = { fg = colors.base03, bg = colors.base01, italic = config.italic },
    FoldColumn = { fg = colors.base03, bg = colors.base01 },
    Cursor = { bg = colors.base06, fg = colors.base01 },
    TermCursor = { link = "Cursor" },
    vCursor = { link = "Cursor" },
    iCursor = { link = "Cursor" },
    lCursor = { link = "Cursor" },
    Special = { link = "base09" },
    Comment = { fg = colors.base03, italic = config.italic },
    Todo = { fg = colors.base04, bold = config.bold, italic = config.italic },
    Done = { fg = colors.base09, bold = config.bold, italic = config.italic },
    Error = { fg = colors.base08, bold = config.bold, reverse = config.inverse },
    Statement = { link = "base08" },
    Conditional = { link = "base08" },
    Repeat = { link = "base08" },
    Label = { link = "base08" },
    Exception = { link = "base08" },
    Operator = { fg = colors.base09, italic = config.italic },
    Keyword = { link = "base08" },
    Identifier = { link = "base0D" },
    Function = { link = "base0BBold" },
    PreProc = { link = "base0C" },
    Include = { link = "base0C" },
    Define = { link = "base0C" },
    Macro = { link = "base0C" },
    PreCondit = { link = "base0C" },
    Constant = { link = "base0E" },
    Character = { link = "base0E" },
    String = { fg = colors.base0B, italic = config.italic },
    Boolean = { link = "base0E" },
    Number = { link = "base0E" },
    Float = { link = "base0E" },
    Type = { link = "base0A" },
    StorageClass = { link = "base09" },
    Structure = { link = "base0C" },
    Typedef = { link = "base0A" },
    Pmenu = { fg = colors.base05, bg = colors.base02 },
    PmenuSel = { fg = colors.base02, bg = colors.base0D, bold = config.bold },
    PmenuSbar = { bg = colors.base02 },
    PmenuThumb = { bg = colors.base03 },
    DiffDelete = { fg = colors.base08, bg = colors.base00, reverse = config.inverse },
    DiffAdd = { fg = colors.base0B, bg = colors.base00, reverse = config.inverse },
    DiffChange = { fg = colors.base0C, bg = colors.base00, reverse = config.inverse },
    DiffText = { fg = colors.base0A, bg = colors.base00, reverse = config.inverse },
    SpellCap = { link = "base0DUnderline" },
    SpellBad = { link = "base08Underline" },
    SpellLocal = { link = "base0CUnderline" },
    SpellRare = { link = "base0EUnderline" },

    -- LSP Diagnostic
    DiagnosticError = { link = "base08" },
    DiagnosticSignError = { link = "base08Sign" },
    DiagnosticUnderlineError = { link = "base08Underline" },
    DiagnosticWarn = { link = "base0A" },
    DiagnosticSignWarn = { link = "base0ASign" },
    DiagnosticUnderlineWarn = { link = "base0AUnderline" },
    DiagnosticInfo = { link = "base0D" },
    DiagnosticSignInfo = { link = "base0DSign" },
    DiagnosticUnderlineInfo = { link = "base0DUnderline" },
    DiagnosticHint = { link = "base0C" },
    DiagnosticSignHint = { link = "base0CSign" },
    DiagnosticUnderlineHint = { link = "base0CUnderline" },
    DiagnosticFloatingError = { link = "base08" },
    DiagnosticFloatingWarn = { link = "base09" },
    DiagnosticFloatingInfo = { link = "base0D" },
    DiagnosticFloatingHint = { link = "base0C" },
    DiagnosticVirtualTextError = { link = "base08" },
    DiagnosticVirtualTextWarn = { link = "base0A" },
    DiagnosticVirtualTextInfo = { link = "base0D" },
    DiagnosticVirtualTextHint = { link = "base0C" },
    LspReferenceRead = { link = "base0ABold" },
    LspReferenceText = { link = "base0ABold" },
    LspReferenceWrite = { link = "base09Bold" },
    LspCodeLens = { link = "base03" },

    -- nvim-treesitter (0.8 compat)
    -- Adapted from https://github.com/nvim-treesitter/nvim-treesitter/commit/42ab95d5e11f247c6f0c8f5181b02e816caa4a4f#commitcomment-87014462
    ["@comment"] = { link = "Comment" },
    ["@none"] = { bg = "NONE", fg = "NONE" },
    ["@preproc"] = { link = "PreProc" },
    ["@define"] = { link = "Define" },
    ["@operator"] = { link = "Operator" },
    ["@punctuation.delimiter"] = { link = "Delimiter" },
    ["@punctuation.bracket"] = { link = "Delimiter" },
    ["@punctuation.special"] = { link = "Delimiter" },
    ["@string"] = { link = "String" },
    ["@string.regex"] = { link = "String" },
    ["@string.escape"] = { link = "SpecialChar" },
    ["@string.special"] = { link = "SpecialChar" },
    ["@character"] = { link = "Character" },
    ["@character.special"] = { link = "SpecialChar" },
    ["@boolean"] = { link = "Boolean" },
    ["@number"] = { link = "Number" },
    ["@float"] = { link = "Float" },
    ["@function"] = { link = "Function" },
    ["@function.call"] = { link = "Function" },
    ["@function.builtin"] = { link = "Special" },
    ["@function.macro"] = { link = "Macro" },
    ["@method"] = { link = "Function" },
    ["@method.call"] = { link = "Function" },
    ["@constructor"] = { link = "Special" },
    ["@parameter"] = { link = "Identifier" },
    ["@keyword"] = { link = "Keyword" },
    ["@keyword.function"] = { link = "Keyword" },
    ["@keyword.return"] = { link = "Keyword" },
    ["@conditional"] = { link = "Conditional" },
    ["@repeat"] = { link = "Repeat" },
    ["@debug"] = { link = "Debug" },
    ["@label"] = { link = "Label" },
    ["@include"] = { link = "Include" },
    ["@exception"] = { link = "Exception" },
    ["@type"] = { link = "Type" },
    ["@type.builtin"] = { link = "Type" },
    ["@type.qualifier"] = { link = "Type" },
    ["@type.definition"] = { link = "Typedef" },
    ["@storageclass"] = { link = "StorageClass" },
    ["@attribute"] = { link = "PreProc" },
    ["@field"] = { link = "Identifier" },
    ["@property"] = { link = "Identifier" },
    ["@variable"] = { link = "base05" },
    ["@variable.builtin"] = { link = "Special" },
    ["@constant"] = { link = "Constant" },
    ["@constant.builtin"] = { link = "Special" },
    ["@constant.macro"] = { link = "Define" },
    ["@namespace"] = { link = "Include" },
    ["@symbol"] = { link = "Identifier" },
    ["@text"] = { link = "base05" },
    ["@text.title"] = { link = "Title" },
    ["@text.literal"] = { link = "String" },
    ["@text.uri"] = { link = "Underlined" },
    ["@text.math"] = { link = "Special" },
    ["@text.environment"] = { link = "Macro" },
    ["@text.environment.name"] = { link = "Type" },
    ["@text.reference"] = { link = "Constant" },
    ["@text.todo"] = { link = "Todo" },
    ["@text.todo.unchecked"] = { link = "Todo" },
    ["@text.todo.checked"] = { link = "Done" },
    ["@text.note"] = { link = "SpecialComment" },
    ["@text.warning"] = { link = "WarningMsg" },
    ["@text.danger"] = { link = "ErrorMsg" },
    ["@text.diff.add"] = { link = "diffAdded" },
    ["@text.diff.delete"] = { link = "diffRemoved" },
    ["@tag"] = { link = "Tag" },
    ["@tag.attribute"] = { link = "Identifier" },
    ["@tag.delimiter"] = { link = "Delimiter" },

    -- nvim-treesitter (0.8 overrides)
    ["@text.strong"] = { bold = config.bold },
    ["@text.strike"] = { strikethrough = config.strikethrough },
    ["@text.emphasis"] = { italic = config.italic },
    ["@text.underline"] = { underline = config.underline },
    ["@keyword.operator"] = { link = "base08" },

    -- gitcommit
    gitcommitSelectedFile = { link = "base0B" },
    gitcommitDiscardedFile = { link = "base08" },

    -- gitsigns.nvim
    GitSignsAdd = { link = "base0BSign" },
    GitSignsChange = { link = "base0CSign" },
    GitSignsDelete = { link = "base08Sign" },

    -- nvim-tree
    NvimTreeSymlink = { fg = colors.base0C },
    NvimTreeRootFolder = { fg = colors.base0E, bold = true },
    NvimTreeFolderIcon = { fg = colors.base0D, bold = true },
    NvimTreeFileIcon = { fg = colors.light2 },
    NvimTreeExecFile = { fg = colors.base0B, bold = true },
    NvimTreeOpenedFile = { fg = colors.bright_base08, bold = true },
    NvimTreeSpecialFile = { fg = colors.base0A, bold = true, underline = true },
    NvimTreeImageFile = { fg = colors.base0E },
    NvimTreeIndentMarker = { fg = colors.dark3 },
    NvimTreeGitDirty = { fg = colors.base0A },
    NvimTreeGitStaged = { fg = colors.base0A },
    NvimTreeGitMerge = { fg = colors.base0E },
    NvimTreeGitRenamed = { fg = colors.base0E },
    NvimTreeGitNew = { fg = colors.base0A },
    NvimTreeGitDeleted = { fg = colors.base08 },
    NvimTreeWindowPicker = { bg = colors.faded_base0C },

    -- termdebug
    debugPC = { bg = colors.faded_base0D },
    debugBreakpoint = { link = "base08Sign" },

    -- netrw
    netrwDir = { link = "base0C" },
    netrwClassify = { link = "base0C" },
    netrwLink = { link = "base03" },
    netrwSymLink = { link = "base05" },
    netrwExe = { link = "base0A" },
    netrwComment = { link = "base03" },
    netrwList = { link = "base0D" },
    netrwHelpCmd = { link = "base0C" },
    netrwCmdSep = { link = "base07" },
    netrwVersion = { link = "base0B" },

    -- telescope.nvim
    TelescopeNormal = { link = "base05" },
    TelescopeSelection = { link = "base09Bold" },
    TelescopeSelectionCaret = { link = "base08" },
    TelescopeMultiSelection = { link = "base03" },
    TelescopeBorder = { link = "TelescopeNormal" },
    TelescopePromptBorder = { link = "TelescopeNormal" },
    TelescopeResultsBorder = { link = "TelescopeNormal" },
    TelescopePreviewBorder = { link = "TelescopeNormal" },
    TelescopeMatching = { link = "base0D" },
    TelescopePromptPrefix = { link = "base08" },
    TelescopePrompt = { link = "TelescopeNormal" },

    -- nvim-cmp
    CmpItemAbbr = { link = "base04" },
    CmpItemAbbrDeprecated = { link = "base05" },
    CmpItemAbbrMatch = { link = "base0DBold" },
    CmpItemAbbrMatchFuzzy = { link = "base0DUnderline" },
    CmpItemMenu = { link = "base03" },
    CmpItemKindText = { link = "base09" },
    CmpItemKindMethod = { link = "base0D" },
    CmpItemKindFunction = { link = "base0D" },
    CmpItemKindConstructor = { link = "base0A" },
    CmpItemKindField = { link = "base0D" },
    CmpItemKindClass = { link = "base0A" },
    CmpItemKindInterface = { link = "base0A" },
    CmpItemKindModule = { link = "base0D" },
    CmpItemKindProperty = { link = "base0D" },
    CmpItemKindValue = { link = "base09" },
    CmpItemKindEnum = { link = "base0A" },
    CmpItemKindKeyword = { link = "base0E" },
    CmpItemKindSnippet = { link = "base0B" },
    CmpItemKindFile = { link = "base0D" },
    CmpItemKindEnumMember = { link = "base0C" },
    CmpItemKindConstant = { link = "base09" },
    CmpItemKindStruct = { link = "base0A" },
    CmpItemKindTypeParameter = { link = "base0A" },
    diffAdded = { link = "base0B" },
    diffRemoved = { link = "base08" },
    diffChanged = { link = "base0C" },
    diffFile = { link = "base09" },
    diffNewFile = { link = "base0A" },
    diffLine = { link = "base0D" },

    -- navic (highlight icons)
    NavicIconsFile = { link = "base0D" },
    NavicIconsModule = { link = "base09" },
    NavicIconsNamespace = { link = "base0D" },
    NavicIconsPackage = { link = "base0C" },
    NavicIconsClass = { link = "base0A" },
    NavicIconsMethod = { link = "base0D" },
    NavicIconsProperty = { link = "base0C" },
    NavicIconsField = { link = "base0E" },
    NavicIconsConstructor = { link = "base0D" },
    NavicIconsEnum = { link = "base0E" },
    NavicIconsInterface = { link = "base0B" },
    NavicIconsFunction = { link = "base0D" },
    NavicIconsVariable = { link = "base0E" },
    NavicIconsConstant = { link = "base09" },
    NavicIconsString = { link = "base0B" },
    NavicIconsNumber = { link = "base09" },
    NavicIconsBoolean = { link = "base09" },
    NavicIconsArray = { link = "base09" },
    NavicIconsObject = { link = "base09" },
    NavicIconsKey = { link = "base0C" },
    NavicIconsNull = { link = "base09" },
    NavicIconsEnumMember = { link = "base0A" },
    NavicIconsStruct = { link = "base0E" },
    NavicIconsEvent = { link = "base0A" },
    NavicIconsOperator = { link = "base08" },
    NavicIconsTypeParameter = { link = "base08" },
    NavicText = { link = "White" },
    NavicSeparator = { link = "White" },

    -- html
    htmlTag = { link = "base0CBold" },
    htmlEndTag = { link = "base0CBold" },
    htmlTagName = { link = "base0D" },
    htmlArg = { link = "base09" },
    htmlTagN = { link = "base05" },
    htmlSpecialTagName = { link = "base0D" },
    htmlLink = { fg = colors.base07, underline = config.underline },
    htmlSpecialChar = { link = "base08" },
    htmlBold = { fg = colors.base04, bg = colors.base00, bold = config.bold },
    htmlBoldUnderline = { fg = colors.base04, bg = colors.base00, bold = config.bold, underline = config.underline },
    htmlBoldItalic = { fg = colors.base04, bg = colors.base00, bold = config.bold, italic = config.italic },
    htmlBoldUnderlineItalic = {
      fg = colors.base04,
      bg = colors.base00,
      bold = config.bold,
      italic = config.italic,
      underline = config.underline,
    },
    htmlUnderline = { fg = colors.base04, bg = colors.base00, underline = config.underline },
    htmlUnderlineItalic = {
      fg = colors.base04,
      bg = colors.base00,
      italic = config.italic,
      underline = config.underline,
    },
    htmlItalic = { fg = colors.base04, bg = colors.base00, bold = config.italic },

    -- xml
    xmlTag = { link = "base0CBold" },
    xmlEndTag = { link = "base0CBold" },
    xmlTagName = { link = "base0D" },
    xmlEqual = { link = "base0D" },
    docbkKeyword = { link = "base0CBold" },
    xmlDocTypeDecl = { link = "base03" },
    xmlDocTypeKeyword = { link = "base0E" },
    xmlCdataStart = { link = "base03" },
    xmlCdataCdata = { link = "base0E" },
    dtdFunction = { link = "base03" },
    dtdTagName = { link = "base0E" },
    xmlAttrib = { link = "base09" },
    xmlProcessingDelim = { link = "base03" },
    dtdParamEntityPunct = { link = "base03" },
    dtdParamEntityDPunct = { link = "base03" },
    xmlAttribPunct = { link = "base03" },
    xmlEntity = { link = "base08" },
    xmlEntityPunct = { link = "base08" },

    -- clojure
    clojureKeyword = { link = "base0D" },
    clojureCond = { link = "base09" },
    clojureSpecial = { link = "base09" },
    clojubase08efine = { link = "base09" },
    clojureFunc = { link = "base0A" },
    clojureRepeat = { link = "base0A" },
    clojureCharacter = { link = "base0C" },
    clojureStringEscape = { link = "base0C" },
    clojureException = { link = "base08" },
    clojureRegexp = { link = "base0C" },
    clojureRegexpEscape = { link = "base0C" },
    clojureRegexpCharClass = { fg = colors.base07, bold = config.bold },
    clojureRegexpMod = { link = "clojureRegexpCharClass" },
    clojureRegexpQuantifier = { link = "clojureRegexpCharClass" },
    clojureParen = { link = "base07" },
    clojureAnonArg = { link = "base0A" },
    clojureVariable = { link = "base0D" },
    clojureMacro = { link = "base09" },
    clojureMeta = { link = "base0A" },
    clojubase08eref = { link = "base0A" },
    clojureQuote = { link = "base0A" },
    clojureUnquote = { link = "base0A" },

    -- C
    cOperator = { link = "base0E" },
    cppOperator = { link = "base0E" },
    cStructure = { link = "base09" },

    -- python
    pythonBuiltin = { link = "base09" },
    pythonBuiltinObj = { link = "base09" },
    pythonBuiltinFunc = { link = "base09" },
    pythonFunction = { link = "base0C" },
    pythonDecorator = { link = "base08" },
    pythonInclude = { link = "base0D" },
    pythonImport = { link = "base0D" },
    pythonRun = { link = "base0D" },
    pythonCoding = { link = "base0D" },
    pythonOperator = { link = "base08" },
    pythonException = { link = "base08" },
    pythonExceptions = { link = "base0E" },
    pythonBoolean = { link = "base0E" },
    pythonDot = { link = "base07" },
    pythonConditional = { link = "base08" },
    pythonRepeat = { link = "base08" },
    pythonDottedName = { link = "base0BBold" },

    -- CSS
    cssBraces = { link = "base0D" },
    cssFunctionName = { link = "base0A" },
    cssIdentifier = { link = "base09" },
    cssClassName = { link = "base0B" },
    cssColor = { link = "base0D" },
    cssSelectorOp = { link = "base0D" },
    cssSelectorOp2 = { link = "base0D" },
    cssImportant = { link = "base0B" },
    cssVendor = { link = "base05" },
    cssTextProp = { link = "base0C" },
    cssAnimationProp = { link = "base0C" },
    cssUIProp = { link = "base0A" },
    cssTransformProp = { link = "base0C" },
    cssTransitionProp = { link = "base0C" },
    cssPrintProp = { link = "base0C" },
    cssPositioningProp = { link = "base0A" },
    cssBoxProp = { link = "base0C" },
    cssFontDescriptorProp = { link = "base0C" },
    cssFlexibleBoxProp = { link = "base0C" },
    cssBorderOutlineProp = { link = "base0C" },
    cssBackgroundProp = { link = "base0C" },
    cssMarginProp = { link = "base0C" },
    cssListProp = { link = "base0C" },
    cssTableProp = { link = "base0C" },
    cssFontProp = { link = "base0C" },
    cssPaddingProp = { link = "base0C" },
    cssDimensionProp = { link = "base0C" },
    cssRenderProp = { link = "base0C" },
    cssColorProp = { link = "base0C" },
    cssGeneratedContentProp = { link = "base0C" },

    -- javascript
    javaScriptBraces = { link = "base05" },
    javaScriptFunction = { link = "base0C" },
    javaScriptIdentifier = { link = "base08" },
    javaScriptMember = { link = "base0D" },
    javaScriptNumber = { link = "base0E" },
    javaScriptNull = { link = "base0E" },
    javaScriptParens = { link = "base07" },

    -- typescript
    typescriptReserved = { link = "base0C" },
    typescriptLabel = { link = "base0C" },
    typescriptFuncKeyword = { link = "base0C" },
    typescriptIdentifier = { link = "base09" },
    typescriptBraces = { link = "base05" },
    typescriptEndColons = { link = "base05" },
    typescriptDOMObjects = { link = "base05" },
    typescriptAjaxMethods = { link = "base05" },
    typescriptLogicSymbols = { link = "base05" },
    typescriptDocSeeTag = { link = "Comment" },
    typescriptDocParam = { link = "Comment" },
    typescriptDocTags = { link = "vimCommentTitle" },
    typescriptGlobalObjects = { link = "base05" },
    typescriptParens = { link = "base07" },
    typescriptOpSymbols = { link = "base07" },
    typescriptHtmlElemProperties = { link = "base05" },
    typescriptNull = { link = "base0E" },
    typescriptInterpolationDelimiter = { link = "base0C" },

    -- ruby
    rubyStringDelimiter = { link = "base0B" },
    rubyInterpolationDelimiter = { link = "base0C" },
    rubyDefinedOperator = { link = "rubyKeyword" },

    -- objc
    objcTypeModifier = { link = "base08" },
    objcDirective = { link = "base0D" },

    -- go
    goDirective = { link = "base0C" },
    goConstants = { link = "base0E" },
    goDeclaration = { link = "base08" },
    goDeclType = { link = "base0D" },
    goBuiltins = { link = "base09" },

    -- lua
    luaIn = { link = "base08" },
    luaFunction = { link = "base0C" },
    luaTable = { link = "base09" },

    -- moonscript
    moonSpecialOp = { link = "base07" },
    moonExtendedOp = { link = "base07" },
    moonFunction = { link = "base07" },
    moonObject = { link = "base0A" },

    -- java
    javaAnnotation = { link = "base0D" },
    javaDocTags = { link = "base0C" },
    javaCommentTitle = { link = "vimCommentTitle" },
    javaParen = { link = "base07" },
    javaParen1 = { link = "base07" },
    javaParen2 = { link = "base07" },
    javaParen3 = { link = "base07" },
    javaParen4 = { link = "base07" },
    javaParen5 = { link = "base07" },
    javaOperator = { link = "base09" },
    javaVarArg = { link = "base0B" },

    -- markdown
    markdownItalic = { fg = colors.base07, italic = config.italic },
    markdownBold = { fg = colors.base07, bold = config.bold },
    markdownBoldItalic = { fg = colors.base07, bold = config.bold, italic = config.italic },
    markdownH1 = { link = "base0BBold" },
    markdownH2 = { link = "base0BBold" },
    markdownH3 = { link = "base0ABold" },
    markdownH4 = { link = "base0ABold" },
    markdownH5 = { link = "base0A" },
    markdownH6 = { link = "base0A" },
    markdownCode = { link = "base0C" },
    markdownCodeBlock = { link = "base0C" },
    markdownCodeDelimiter = { link = "base0C" },
    markdownBlockquote = { link = "base03" },
    markdownListMarker = { link = "base03" },
    markdownOrdebase08ListMarker = { link = "base03" },
    markdownRule = { link = "base03" },
    markdownHeadingRule = { link = "base03" },
    markdownUrlDelimiter = { link = "base07" },
    markdownLinkDelimiter = { link = "base07" },
    markdownLinkTextDelimiter = { link = "base07" },
    markdownHeadingDelimiter = { link = "base09" },
    markdownUrl = { link = "base0E" },
    markdownUrlTitleDelimiter = { link = "base0B" },
    markdownLinkText = { fg = colors.base03, underline = config.underline },
    markdownIdDeclaration = { link = "markdownLinkText" },

    -- haskell
    haskellType = { link = "base0D" },
    haskellIdentifier = { link = "base0C" },
    haskellSeparator = { link = "base07" },
    haskellDelimiter = { link = "base09" },
    haskellOperators = { link = "base0E" },
    haskellBacktick = { link = "base09" },
    haskellStatement = { link = "base0E" },
    haskellConditional = { link = "base0E" },
    haskellLet = { link = "base08" },
    haskellDefault = { link = "base08" },
    haskellWhere = { link = "base08" },
    haskellBottom = { link = "base08Bold" },
    haskellImportKeywords = { link = "base0EBold" },
    haskellDeclKeyword = { link = "base09" },
    haskellDecl = { link = "base09" },
    haskellDeriving = { link = "base0E" },
    haskellAssocType = { link = "base0C" },
    haskellNumber = { link = "base0C" },
    haskellPragma = { link = "base08Bold" },
    haskellTH = { link = "base0CBold" },
    haskellForeignKeywords = { link = "base0B" },
    haskellKeyword = { link = "base08" },
    haskellFloat = { link = "base0C" },
    haskellInfix = { link = "base0E" },
    haskellQuote = { link = "base0BBold" },
    haskellShebang = { link = "base0ABold" },
    haskellLiquid = { link = "base0EBold" },
    haskellQuasiQuoted = { link = "base0DBold" },
    haskellRecursiveDo = { link = "base0E" },
    haskellQuotedType = { link = "base08" },
    haskellPreProc = { link = "base07" },
    haskellTypeRoles = { link = "base08Bold" },
    haskellTypeForall = { link = "base08" },
    haskellPatternKeyword = { link = "base0D" },

    -- json
    jsonKeyword = { link = "base0B" },
    jsonQuote = { link = "base0B" },
    jsonBraces = { link = "base05" },
    jsonString = { link = "base05" },

    -- mail
    mailQuoted1 = { link = "base0C" },
    mailQuoted2 = { link = "base0E" },
    mailQuoted3 = { link = "base0A" },
    mailQuoted4 = { link = "base0B" },
    mailQuoted5 = { link = "base08" },
    mailQuoted6 = { link = "base09" },
    mailSignature = { link = "Comment" },

    -- c#
    csBraces = { link = "base05" },
    csEndColon = { link = "base05" },
    csLogicSymbols = { link = "base05" },
    csParens = { link = "base07" },
    csOpSymbols = { link = "base07" },
    csInterpolationDelimiter = { link = "base07" },
    csInterpolationAlignDel = { link = "base0CBold" },
    csInterpolationFormat = { link = "base0C" },
    csInterpolationFormatDel = { link = "base0CBold" },

    -- rust btw
    rustSigil = { link = "base09" },
    rustEscape = { link = "base0C" },
    rustStringContinuation = { link = "base0C" },
    rustEnum = { link = "base0C" },
    rustStructure = { link = "base0C" },
    rustModPathSep = { link = "base06" },
    rustCommentLineDoc = { link = "Comment" },
    rustDefault = { link = "base0C" },

    -- ocaml
    ocamlOperator = { link = "base05" },
    ocamlKeyChar = { link = "base09" },
    ocamlArrow = { link = "base09" },
    ocamlInfixOpKeyword = { link = "base08" },
    ocamlConstructor = { link = "base09" },

    -- lspsaga.nvim
    LspSagaCodeActionTitle = { link = "Title" },
    LspSagaCodeActionBorder = { link = "base05" },
    LspSagaCodeActionContent = { fg = colors.base0B, bold = config.bold },
    LspSagaLspFinderBorder = { link = "base05" },
    LspSagaAutoPreview = { link = "base09" },
    TargetWord = { fg = colors.base0D, bold = config.bold },
    FinderSeparator = { link = "base0C" },
    LspSagaDefPreviewBorder = { link = "base0D" },
    LspSagaHoverBorder = { link = "base09" },
    LspSagaRenameBorder = { link = "base0D" },
    LspSagaDiagnosticSource = { link = "base09" },
    LspSagaDiagnosticBorder = { link = "base0E" },
    LspSagaDiagnosticHeader = { link = "base0B" },
    LspSagaSignatureHelpBorder = { link = "base0B" },
    SagaShadow = { link = "base00" },

    -- dashboard-nvim
    DashboardShortCut = { link = "base09" },
    DashboardHeader = { link = "base0C" },
    DashboardCenter = { link = "base0A" },
    DashboardFooter = { fg = colors.base0E, italic = config.italic },

    -- mason
    MasonHighlight = { fg = colors.base0D },
    MasonHighlightBlock = { fg = colors.base00, bg = colors.base0D },
    MasonHighlightBlockBold = { fg = colors.base00, bg = colors.base0D, bold = true },
    MasonHighlightSecondary = { fg = colors.base0A },
    MasonHighlightBlockSecondary = { fg = colors.base00, bg = colors.base0A },
    MasonHighlightBlockBoldSecondary = { fg = colors.base00, bg = colors.base0A, bold = true },
    MasonHeader = { link = "MasonHighlightBlockBoldSecondary" },
    MasonHeaderSecondary = { link = "MasonHighlightBlockBold" },
    MasonMuted = { fg = colors.base07 },
    MasonMutedBlock = { fg = colors.base00, bg = colors.base07 },
    MasonMutedBlockBold = { fg = colors.base00, bg = colors.base07, bold = true },
}

return groups
